
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laypgxnvhfpdbdxxmapc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxheXBneG52aGZwZGJkeHhtYXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyOTE5OTIsImV4cCI6MjA1NDg2Nzk5Mn0.FsZqrWRQ69w_KMLj6IUbAYDHrm8MMwnny3Cu6yEL6pM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
